---
- name: docker dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}"
    - apt-transport-https
    - ca-certificates
    - python3
    - python3-pip
    - python3-httplib2

- name: (Ubuntu) add docker apt key
  apt_key:
    url: "{{ apt_docker_key }}"
    id: "{{ apt_docker_key_id }}"
    state: present

- name: add docker apt repository
  apt_repository:
    repo: "{{ apt_docker_repo }}"
    update_cache: yes
    mode: 0644

- name: install docker
  apt:
    name: docker-engine

