---
- yum_repository:
    name: Docker-Yum-7
    description: Docker-YUM
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: true
    sslverify: true
    enabled: true
  when: ansible_distribution_version >= '7'

- yum_repository:
    name: Docker-Yum-6
    description: Docker-YUM
    baseurl: https://yum.dockerproject.org/repo/main/centos/6/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: true
    sslverify: true
    enabled: true
  when: ansible_distribution_version <= '7'

- name: install docker
  package: >
    name=docker-engine
    state=latest
