---

- yum_repository:
    name: Docker-Yum
    description: Docker-YUM
    baseurl: "{{docker_repo }}"
    gpgkey: "{{ docker_repo_gpgkey_url }}"
    gpgcheck: "{{ docker_repo_gpgcheck }}"
    sslverify: "{{ docker_repo_ssl_verify }}"
    enabled: "{{ docker_repo_enabled }}"

- name: Require EPEL for Python Pip
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release

- name: install docker
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-engine
    - python
    - python-pip
    - python-httplib2
