---
- name: docker dependencies
  apt: name={{ item }}
  with_items:
    - "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}"
    - apt-transport-https
    - ca-certificates

- name : (Ubuntu) add docker apt key
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id='58118E89F3A912897C070ADBF76221572C52609D'

- name: add docker apt repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    mode: "0644"

- name: fix apt file perms for docker
  file:
    path: /etc/apt/sources.list.d/apt_dockerproject_org_repo.list
    owner: root
    group: root
    mode: 0664
    state: present

- name: install docker
  apt: name=docker-engine

