---
- name: docker dependencies
  apt: name={{ item }}
  with_items:
    - "linux-image-extra-virtual-lts-{{ ansible_distribution_release }}"
    - apt-transport-https
    - ca-certificates

- name : (Ubuntu) add docker apt key
  apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id='58118E89F3A912897C070ADBF76221572C52609D'

- name: add docker apt repository
  apt_repository: >
    repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main" update_cache=yes

- name: install docker
  apt: name=docker-engine

